version: '3.9'

services:
  # backend:
  #   container_name: backend
  #   image: backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #     - 5555:5555
  #   environment:
  #     - DATABASE_URL="postgresql://postgres:123@db:5432/capstone?schema=public"

  db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testapp
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
